"""replace_price_billing_cycle_with_per_cycle_prices

Revision ID: 30d9ea37909c
Revises: 9860cbf3aa41
Create Date: 2026-04-08 16:12:24.119057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30d9ea37909c'
down_revision: Union[str, None] = '9860cbf3aa41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saas_subscription_plans', sa.Column('price_monthly', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('saas_subscription_plans', sa.Column('price_quarterly', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('saas_subscription_plans', sa.Column('price_yearly', sa.Numeric(precision=10, scale=2), nullable=True))
    # Back-fill price_monthly from the old price column (same value) before making it NOT NULL
    op.execute("UPDATE saas_subscription_plans SET price_monthly = price WHERE price_monthly IS NULL")
    op.execute("UPDATE saas_subscription_plans SET price_monthly = 0 WHERE price_monthly IS NULL")
    op.alter_column('saas_subscription_plans', 'price_monthly', nullable=False)
    op.drop_column('saas_subscription_plans', 'price')
    op.drop_column('saas_subscription_plans', 'billing_cycle')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saas_subscription_plans', sa.Column('billing_cycle', postgresql.ENUM('MONTHLY', 'QUARTERLY', 'YEARLY', name='billingcycle'), autoincrement=False, nullable=False))
    op.add_column('saas_subscription_plans', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('saas_subscription_plans', 'price_yearly')
    op.drop_column('saas_subscription_plans', 'price_quarterly')
    op.drop_column('saas_subscription_plans', 'price_monthly')
    # ### end Alembic commands ###
