"""drop_orphaned_country_column_from_client_subscription_plans

Revision ID: 68344d2921de
Revises: e2c5f9a1b047
Create Date: 2026-04-12 19:22:08.756070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68344d2921de'
down_revision: Union[str, None] = 'e2c5f9a1b047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop orphaned country column/index left by old version of e2c5f9a1b047
    op.execute("DROP INDEX IF EXISTS ix_client_subscription_plans_country")
    op.execute("ALTER TABLE client_subscription_plans DROP COLUMN IF EXISTS country")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_content_videos_client_slug', table_name='content_videos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_content_videos_client_slug', 'content_videos', ['client_id', 'slug'], unique=True)
    # ### end Alembic commands ###
