"""add_plan_new_fields_soft_delete

Revision ID: 9860cbf3aa41
Revises: 
Create Date: 2026-04-08 14:42:13.827173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9860cbf3aa41'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE clients DROP CONSTRAINT IF EXISTS clients_domain_key")
    op.drop_index('ix_clients_domain', table_name='clients')
    op.create_index(op.f('ix_clients_domain'), 'clients', ['domain'], unique=True)
    op.add_column('saas_subscription_plans', sa.Column('sub_text', sa.String(length=500), nullable=True))
    op.add_column('saas_subscription_plans', sa.Column('currency', sa.String(length=10), nullable=False))
    op.add_column('saas_subscription_plans', sa.Column('key_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('saas_subscription_plans', sa.Column('additional_apps', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('saas_subscription_plans', sa.Column('additional_app_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('saas_subscription_plans', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saas_subscription_plans', 'deleted_at')
    op.drop_column('saas_subscription_plans', 'additional_app_price')
    op.drop_column('saas_subscription_plans', 'additional_apps')
    op.drop_column('saas_subscription_plans', 'key_features')
    op.drop_column('saas_subscription_plans', 'currency')
    op.drop_column('saas_subscription_plans', 'sub_text')
    op.drop_index(op.f('ix_clients_domain'), table_name='clients')
    op.create_index('ix_clients_domain', 'clients', ['domain'], unique=False)
    op.create_unique_constraint('clients_domain_key', 'clients', ['domain'])
    # ### end Alembic commands ###
