"""add_usage_and_overage_limits_to_plans

Revision ID: a2b3c4d5e6f7
Revises: 9860cbf3aa41
Create Date: 2026-06-23 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2b3c4d5e6f7'
down_revision: Union[str, None] = 'q5r6s7t8u9v0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Usage Limits (AWS-metered)
    op.add_column('saas_subscription_plans', sa.Column('bandwidth_gb_monthly', sa.Integer(), nullable=True))
    op.add_column('saas_subscription_plans', sa.Column('encoding_minutes_monthly', sa.Integer(), nullable=True))
    op.add_column('saas_subscription_plans', sa.Column('api_calls_per_month', sa.Integer(), nullable=True))
    op.add_column('saas_subscription_plans', sa.Column('concurrent_users_peak', sa.Integer(), nullable=True))
    op.add_column('saas_subscription_plans', sa.Column('simultaneous_uploads', sa.Integer(), nullable=False, server_default='1'))
    
    # Overage Pricing
    op.add_column('saas_subscription_plans', sa.Column('overage_bandwidth_per_gb', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('saas_subscription_plans', sa.Column('overage_storage_per_gb', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('saas_subscription_plans', sa.Column('overage_encoding_per_minute', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('saas_subscription_plans', sa.Column('overage_api_per_1m_calls', sa.Numeric(precision=10, scale=4), nullable=True))
    
    # Content Restrictions
    op.add_column('saas_subscription_plans', sa.Column('allowed_content_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('saas_subscription_plans', sa.Column('max_bitrate_mbps', sa.Integer(), nullable=True))
    op.add_column('saas_subscription_plans', sa.Column('content_retention_days', sa.Integer(), nullable=False, server_default='365'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saas_subscription_plans', 'content_retention_days')
    op.drop_column('saas_subscription_plans', 'max_bitrate_mbps')
    op.drop_column('saas_subscription_plans', 'allowed_content_types')
    op.drop_column('saas_subscription_plans', 'overage_api_per_1m_calls')
    op.drop_column('saas_subscription_plans', 'overage_encoding_per_minute')
    op.drop_column('saas_subscription_plans', 'overage_storage_per_gb')
    op.drop_column('saas_subscription_plans', 'overage_bandwidth_per_gb')
    op.drop_column('saas_subscription_plans', 'simultaneous_uploads')
    op.drop_column('saas_subscription_plans', 'concurrent_users_peak')
    op.drop_column('saas_subscription_plans', 'api_calls_per_month')
    op.drop_column('saas_subscription_plans', 'encoding_minutes_monthly')
    op.drop_column('saas_subscription_plans', 'bandwidth_gb_monthly')
    # ### end Alembic commands ###
