"""add_categories_media_assets

Revision ID: b52c6d6dcf09
Revises: 30d9ea37909c
Create Date: 2026-04-09 12:18:22.604162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b52c6d6dcf09'
down_revision: Union[str, None] = '30d9ea37909c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
