"""category_asset_fks

Revision ID: ff421573efb2
Revises: b52c6d6dcf09
Create Date: 2026-04-09 18:11:49.837550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff421573efb2'
down_revision: Union[str, None] = 'b52c6d6dcf09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE content_categories ADD COLUMN IF NOT EXISTS thumbnail_asset_id UUID")
    op.execute("ALTER TABLE content_categories ADD COLUMN IF NOT EXISTS banner_asset_id UUID")
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.table_constraints tc
                JOIN information_schema.constraint_column_usage ccu USING (constraint_name)
                WHERE tc.table_name = 'content_categories'
                  AND tc.constraint_type = 'FOREIGN KEY'
                  AND ccu.column_name = 'thumbnail_asset_id'
            ) THEN
                ALTER TABLE content_categories
                ADD CONSTRAINT fk_categories_thumbnail
                FOREIGN KEY (thumbnail_asset_id) REFERENCES media_assets(id) ON DELETE SET NULL;
            END IF;
        END;
        $$
    """)
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.table_constraints tc
                JOIN information_schema.constraint_column_usage ccu USING (constraint_name)
                WHERE tc.table_name = 'content_categories'
                  AND tc.constraint_type = 'FOREIGN KEY'
                  AND ccu.column_name = 'banner_asset_id'
            ) THEN
                ALTER TABLE content_categories
                ADD CONSTRAINT fk_categories_banner
                FOREIGN KEY (banner_asset_id) REFERENCES media_assets(id) ON DELETE SET NULL;
            END IF;
        END;
        $$
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content_categories', type_='foreignkey')
    op.drop_constraint(None, 'content_categories', type_='foreignkey')
    op.drop_column('content_categories', 'banner_asset_id')
    op.drop_column('content_categories', 'thumbnail_asset_id')
    # ### end Alembic commands ###
