/**
 * API Endpoint Definitions
 *
 * All paths are relative to NEXT_PUBLIC_API_URL (e.g. /api/v1).
 * Import these constants instead of hardcoding strings in service files.
 */

export const ENDPOINTS = {
    // ── Auth ─────────────────────────────────────────────────────────────────
    auth: {
        login: "/auth/login",  // Unified login — handles both superadmin and client-admin
        forgotPassword: "/auth/forgot-password",
        resetPassword: "/auth/reset-password",
        superadmin: {
            login: "/auth/superadmin/login",
            refresh: "/auth/superadmin/refresh",
            forgotPassword: "/auth/superadmin/forgot-password",
            resetPassword: "/auth/superadmin/reset-password",
            changePassword: "/auth/superadmin/change-password",
            me: "/auth/superadmin/me",
        },
        clientAdmin: {
            login: "/auth/admin/login",
            signup: "/auth/admin/signup",
            refresh: "/auth/admin/refresh",
            forgotPassword: "/auth/admin/forgot-password",
            resetPassword: "/auth/admin/reset-password",
            changePassword: "/auth/admin/change-password",
            me: "/auth/admin/me",
        },
        register: "/auth/register",
        verifySignupEmail: "/auth/register/verify-email",
        socialAuthConfig: "/auth/config/social-auth",
    },

    // ── Superadmin ────────────────────────────────────────────────────────────
    superadmin: {
        dashboard: "/superadmin/dashboard",
        dashboardAnalytics: "/superadmin/dashboard/analytics",
        clients: "/superadmin/clients",
        client: (id: string) => `/superadmin/clients/${id}`,
        clientAdminUsers: (id: string) => `/superadmin/clients/${id}/admin-users`,
        clientProvisionDemo: (id: string) => `/superadmin/clients/${id}/provision-demo-content`,
        clientBilling: (id: string) => `/superadmin/billing?client_id=${id}`,
        clientSubscription: (id: string) => `/superadmin/clients/${id}/subscription`,
        plans: "/superadmin/plans",
        plansTrash: "/superadmin/plans/trash",
        plan: (id: string) => `/superadmin/plans/${id}`,
        planToggle: (id: string) => `/superadmin/plans/${id}/toggle`,
        planRestore: (id: string) => `/superadmin/plans/${id}/restore`,
        planPermanent: (id: string) => `/superadmin/plans/${id}/permanent`,
        modules: "/superadmin/modules",
        module: (id: string) => `/superadmin/modules/${id}`,
        billing: "/superadmin/billing",
        settings: "/superadmin/settings",
        settingsEmailTest: "/superadmin/settings/email/test",
        usage: "/superadmin/usage",
        clientUsage: (id: string) => `/superadmin/usage/${id}`,
        usageRecord: "/superadmin/usage/record",
        alerts: "/superadmin/alerts",
        alert: (id: string) => `/superadmin/alerts/${id}`,
        alertAcknowledge: (id: string) => `/superadmin/alerts/${id}/acknowledge`,
        invoice: (clientId: string) => `/superadmin/usage/${clientId}/invoice`,
        mailLogs: "/superadmin/mail-logs",
        jobs: "/superadmin/jobs",
        jobRun: (jobId: string) => `/superadmin/jobs/${jobId}/run`,
        demoContent: "/superadmin/demo-content",
        demoContentItem: (id: string) => `/superadmin/demo-content/${id}`,
        demoContentTranscode: (id: string) => `/superadmin/demo-content/${id}/transcode`,
        demoAssets: {
            presign: "/superadmin/demo-assets/presign",
            confirm: "/superadmin/demo-assets/confirm",
        },
        demoCategories: "/superadmin/demo-categories",
        demoCategoryItem: (id: string) => `/superadmin/demo-categories/${id}`,
    },

    // ── Client Admin ──────────────────────────────────────────────────────────
    admin: {
        dashboard: "/admin/dashboard",
        dashboardAnalytics: "/admin/dashboard/analytics",
        reports: "/admin/dashboard/reports",
        roles: "/admin/roles",
        role: (id: string) => `/admin/roles/${id}`,
        rolePermissions: "/admin/roles/permissions",
        currentRolePermissions: "/admin/roles/me/permissions",
        users: "/admin/users",
        user: (id: string) => `/admin/users/${id}`,
        adminUsers: "/admin/users/admins/list",
        adminUsersCreate: "/admin/users/admins",
        adminUser: (id: string) => `/admin/users/admins/${id}`,
        adminUserResendInvitation: (id: string) => `/admin/users/admins/${id}/resend-invitation`,
        contentPartners: "/admin/content-partners",
        contentPartner: (id: string) => `/admin/content-partners/${id}`,
        content: "/admin/content",
        categories: "/admin/content/categories",
        category: (id: string) => `/admin/content/categories/${id}`,
        audios: "/admin/content/audios",
        audiosTrash: "/admin/content/audios/trash",
        audio: (id: string) => `/admin/content/audios/${id}`,
        audioRestore: (id: string) => `/admin/content/audios/${id}/restore`,
        audioPermanent: (id: string) => `/admin/content/audios/${id}/permanent`,
        videos: "/admin/content/videos",
        videosTrash: "/admin/content/videos/trash",
        video: (id: string) => `/admin/content/videos/${id}`,
        videoRestore: (id: string) => `/admin/content/videos/${id}/restore`,
        videoPermanent: (id: string) => `/admin/content/videos/${id}/permanent`,
        ppvEvents: "/admin/content/ppv",
        ppvEvent: (id: string) => `/admin/content/ppv/${id}`,
        ppvEventRegenerateKey: (id: string) => `/admin/content/ppv/${id}/regenerate-key`,
        ppvEventToggleLive: (id: string) => `/admin/content/ppv/${id}/toggle-live`,
        liveTvChannels: "/admin/content/live-streams",
        liveTvChannel: (id: string) => `/admin/content/live-streams/${id}`,
        liveTvToggleLive: (id: string) => `/admin/content/live-streams/${id}/toggle-live`,
        liveTvRegenerateKey: (id: string) => `/admin/content/live-streams/${id}/regenerate-key`,
        // EPG
        epgChannels: "/admin/content/epg/channels",
        epgPrograms: (channelId: string) => `/admin/content/epg/${channelId}/programs`,
        epgProgram: (programId: string) => `/admin/content/epg/programs/${programId}`,
        epgReorder: (channelId: string) => `/admin/content/epg/${channelId}/programs/reorder`,
        epgImport: (channelId: string) => `/admin/content/epg/${channelId}/import`,
        epgSchedule: (channelId: string) => `/admin/content/epg/${channelId}/schedule`,
        series: "/admin/content/series",
        seriesTrash: "/admin/content/series/trash",
        seriesItem: (id: string) => `/admin/content/series/${id}`,
        seriesRestore: (id: string) => `/admin/content/series/${id}/restore`,
        seriesPermanent: (id: string) => `/admin/content/series/${id}/permanent`,
        seriesEpisodes: (id: string) => `/admin/content/series/${id}/episodes`,
        seriesEpisode: (seriesId: string, episodeId: string) => `/admin/content/series/${seriesId}/episodes/${episodeId}`,
        // Monetization
        subscriptions: "/admin/subscriptions",
        subscriptionUsers: "/admin/subscriptions/users",
        subscriptionPlans: "/admin/subscriptions/plans",
        subscriptionPlan: (id: string) => `/admin/subscriptions/plans/${id}`,
        subscriptionPlansReorder: "/admin/subscriptions/plans/reorder",
        pricingPlans: "/admin/subscriptions/plans",
        pricingPlan: (id: string) => `/admin/subscriptions/plans/${id}`,
        payments: "/admin/payments",
        coupons: "/admin/coupons",
        coupon: (id: string) => `/admin/coupons/${id}`,
        couponUsages: (id: string) => `/admin/coupons/${id}/usages`,
        couponValidate: "/admin/coupons/validate",
        couponStats: "/admin/coupons/stats",
        taxes: "/admin/taxes",
        tax: (id: string) => `/admin/taxes/${id}`,
        advertisements: "/admin/advertisements",
        billing: "/admin/billing",
        billingLicensing: "/admin/billing/licensing",
        billingUpgradeInitiate: "/admin/billing/upgrade/initiate",
        billingUpgradeConfirm: "/admin/billing/upgrade/confirm",
        billingDowngradeRequest: "/admin/billing/downgrade/request",
        billingAutoRenew: "/admin/billing/auto-renew",
        billingPaymentHistory: "/admin/billing/payment-history",
        billingPaymentMethods: "/admin/billing/payment-methods",
        billingPaymentMethodSetup: "/admin/billing/payment-methods/setup",
        // Platform Settings
        themeSettings: "/admin/theme-settings",
        siteSettings: "/admin/site-settings",
        siteSettingsEmailTest: "/admin/site-settings/email/test",
        siteSettingsLogoPresign: "/admin/site-settings/logo/presign",
        platformIssuer: "/admin/site-settings/platform-issuer",
        paymentGateways: "/admin/payment-gateways",
        menus: "/admin/menus",
        menuGroups: "/admin/menus/groups",
        menuGroup: (groupId: string) => `/admin/menus/groups/${groupId}`,
        menuGroupActivate: (groupId: string) => `/admin/menus/groups/${groupId}/activate`,
        menuLinks: (groupId: string) => `/admin/menus/groups/${groupId}/links`,
        menuLink: (groupId: string, linkId: string) => `/admin/menus/groups/${groupId}/links/${linkId}`,
        menuLinksReorder: (groupId: string) => `/admin/menus/groups/${groupId}/links/reorder`,
        upload: {
            presign: "/admin/upload/presign",
            confirm: "/admin/upload/confirm",
            reconcile: "/admin/upload/reconcile",
            multipartInitiate: "/admin/upload/multipart/initiate",
            multipartPresignPart: "/admin/upload/multipart/presign-part",
            multipartComplete: "/admin/upload/multipart/complete",
            multipartAbort: "/admin/upload/multipart/abort",
            mediaLibrary: "/admin/upload/media-library",
            deleteAsset: (id: string) => `/admin/upload/media-assets/${id}`,
        },
        transcoding: {
            trigger: (videoId: string) => `/admin/transcoding/videos/${videoId}/trigger`,
            status: (videoId: string) => `/admin/transcoding/videos/${videoId}/status`,
            keyToken: (videoId: string) => `/admin/transcoding/videos/${videoId}/key-token`,
        },
        pages: "/admin/pages",
        page: (id: string) => `/admin/pages/${id}`,
    },

    // ── DRM key delivery (called by the player, not the admin UI) ─────────────
    drm: {
        key: (videoId: string) => `/drm/key/${videoId}`,
        keyToken: (videoId: string) => `/drm/key-token/${videoId}`,
    },

    // ── CORS-safe HLS proxy (bypasses CloudFront/S3 CORS caching entirely) ────
    media: {
        stream: (videoId: string) => `/media/stream/${videoId}/manifest.m3u8`,
    },

    // ── Public ────────────────────────────────────────────────────────────────
    public: {
        client: "/public/client",
        catalog: "/public/catalog",
        plans: "/public/plans",
        videos: "/public/videos",
        playbackVideo: (id: string) => `/public/playback/video/${id}`,
        advertisementEvent: (id: string) => `/public/ads/${id}/events`,
        liveStreams: "/public/live-streams",
        liveStream: (id: string) => `/public/live-streams/${id}`,
        playbackLiveStream: (id: string) => `/public/playback/live-stream/${id}`,
        liveStreamEpg: (id: string) => `/public/live-streams/${id}/epg`,
    },
} as const;
